FROM blockstack/stacks-blockchain:2.4.0.0.0 as stacks-node

FROM rust:bullseye AS test

WORKDIR /build

RUN apt-get update && \
    apt-get install -y ruby-mustache && \
    rustup component add llvm-tools-preview && \
    cargo install \
      grcov \
      just

ENV RUSTFLAGS="-Cinstrument-coverage" \
    LLVM_PROFILE_FILE="stacks-blockchain-%p-%m.profraw" \
    STACKS_NODE_TEST="1"

COPY --from=stacks-node /bin/stacks-node /bin/

COPY . .

RUN just process-templates && \
    cargo build --workspace && \
    cargo test --workspace --bin=subnet-node --no-run

